<?php

declare(strict_types=1);

namespace App\Analyzer\DebugAnalyzer\Generator;

use App\Analyzer\Graph\Graph;
use App\Analyzer\Graph\Node\BuiltinNode;
use App\Analyzer\Graph\Node\ClassNode;
use App\Analyzer\Graph\Node\ConstantNode;
use App\Analyzer\Graph\Node\EnumCaseNode;
use App\Analyzer\Graph\Node\EnumNode;
use App\Analyzer\Graph\Node\FunctionNode;
use App\Analyzer\Graph\Node\GraphInterfaceNode;
use App\Analyzer\Graph\Node\MethodNode;
use App\Analyzer\Graph\Node\PropertyNode;
use App\Analyzer\Graph\Node\TraitNode;
use App\Analyzer\Graph\NodeId\BuiltinNodeId;
use App\Analyzer\Graph\NodeId\ClassNodeId;
use App\Analyzer\Graph\NodeId\ConstantNodeId;
use App\Analyzer\Graph\NodeId\EnumCaseNodeId;
use App\Analyzer\Graph\NodeId\EnumNodeId;
use App\Analyzer\Graph\NodeId\FunctionNodeId;
use App\Analyzer\Graph\NodeId\InterfaceNodeId;
use App\Analyzer\Graph\NodeId\MethodNodeId;
use App\Analyzer\Graph\NodeId\PropertyNodeId;
use App\Analyzer\Graph\NodeId\TraitNodeId;

/**
 * Generates a whole dependency graph, and routes the recursion between generators.
 *
 * Each kind of symbol is generated by the generator that owns it, and each of those
 * reaches the others back through this class. Being the one implementation of the
 * recursion contract is what lets the generators be constructed in order instead of
 * in a cycle, and what keeps "which generator produces a method" a single fact.
 *
 * @visibility parent
 */
final class GraphGenerator implements SymbolGraphGenerator
{
    /**
     * @param ClassLikeGraphGenerator $classLikes The generator of classes, interfaces, traits and enums
     * @param MemberGraphGenerator    $members    The generator of methods, functions and properties
     * @param LeafGraphGenerator      $leaves     The generator of constants, enum cases and builtin types
     * @param NodeIdGenerator         $ids        The source of identifiers drawn when none is given
     * @param RandomSource            $random     The random source the root symbol is drawn from
     */
    public function __construct(
        private readonly ClassLikeGraphGenerator $classLikes,
        private readonly MemberGraphGenerator $members,
        private readonly LeafGraphGenerator $leaves,
        private readonly NodeIdGenerator $ids,
        private readonly RandomSource $random,
    ) {}

    /**
     * Generates a dependency graph rooted at a drawn top-level symbol.
     *
     * The root is one of the things PHP declares at the top of a file — a class, an
     * interface, a trait or a function — because a graph rooted at a method or a
     * constant would be a fragment rather than a codebase.
     *
     * @param int $depth How many levels of symbols the graph goes down
     *
     * @return Graph A generated dependency graph
     */
    public function graph(int $depth = 5): Graph
    {
        $remaining = $depth - 1;

        return (match ($this->random->numberBetween(1, 4)) {
            1 => $this->classGraph(null, $remaining),
            2 => $this->interfaceGraph(null, $remaining),
            3 => $this->traitGraph(null, $remaining),
            default => $this->functionGraph(null, $remaining),
        })->graph;
    }

    /**
     * Generates the graph of a class.
     *
     * @param null|ClassNodeId $symbol The class to generate, or null to draw one
     * @param int              $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<ClassNode> The class graph
     */
    public function classGraph(?ClassNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->classLikes->classGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of an interface.
     *
     * @param null|InterfaceNodeId $symbol The interface to generate, or null to draw one
     * @param int                  $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<GraphInterfaceNode> The interface graph
     */
    public function interfaceGraph(?InterfaceNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->classLikes->interfaceGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of a trait.
     *
     * @param null|TraitNodeId $symbol The trait to generate, or null to draw one
     * @param int              $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<TraitNode> The trait graph
     */
    public function traitGraph(?TraitNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->classLikes->traitGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of an enum.
     *
     * @param null|EnumNodeId $symbol The enum to generate, or null to draw one
     * @param int             $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<EnumNode> The enum graph
     */
    public function enumGraph(?EnumNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->classLikes->enumGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of a method.
     *
     * @param null|MethodNodeId $symbol The method to generate, or null to draw one
     * @param int               $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<MethodNode> The method graph
     */
    public function methodGraph(?MethodNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->members->methodGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of a function.
     *
     * @param null|FunctionNodeId $symbol The function to generate, or null to draw one
     * @param int                 $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<FunctionNode> The function graph
     */
    public function functionGraph(?FunctionNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->members->functionGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of a property.
     *
     * @param null|PropertyNodeId $symbol The property to generate, or null to draw one
     * @param int                 $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<PropertyNode> The property graph
     */
    public function propertyGraph(?PropertyNodeId $symbol = null, int $depth = 5): GeneratedGraph
    {
        return $this->members->propertyGraph($this, $symbol, $depth);
    }

    /**
     * Generates the graph of a class constant.
     *
     * @param null|ConstantNodeId $symbol The constant to generate, or null to draw one
     *
     * @return GeneratedGraph<ConstantNode> The constant graph
     */
    public function constantGraph(?ConstantNodeId $symbol = null): GeneratedGraph
    {
        return $this->leaves->constantGraph($symbol);
    }

    /**
     * Generates the graph of an enum case.
     *
     * @param null|EnumCaseNodeId $symbol The enum case to generate, or null to draw one
     *
     * @return GeneratedGraph<EnumCaseNode> The enum case graph
     */
    public function enumCaseGraph(?EnumCaseNodeId $symbol = null): GeneratedGraph
    {
        return $this->leaves->enumCaseGraph($symbol);
    }

    /**
     * Generates the graph of a builtin type.
     *
     * @param null|BuiltinNodeId $symbol The builtin type to generate, or null to draw one
     *
     * @return GeneratedGraph<BuiltinNode> The builtin type graph
     */
    public function builtinGraph(?BuiltinNodeId $symbol = null): GeneratedGraph
    {
        return $this->leaves->builtinGraph($symbol);
    }

    /**
     * Generates the graph of whatever stands in a type position.
     *
     * @param null|BuiltinNodeId|ClassNodeId|EnumNodeId|InterfaceNodeId $symbol The type to generate, or null to draw one
     * @param int                                                       $depth  How many further levels of symbols to generate
     *
     * @return GeneratedGraph<BuiltinNode|ClassNode|EnumNode|GraphInterfaceNode> The type graph
     */
    public function typeGraph(
        BuiltinNodeId|ClassNodeId|EnumNodeId|InterfaceNodeId|null $symbol = null,
        int $depth = 5,
    ): GeneratedGraph {
        $symbol ??= $this->ids->typeNodeId();

        return match (true) {
            $symbol instanceof BuiltinNodeId => $this->builtinGraph($symbol),
            $symbol instanceof ClassNodeId => $this->classGraph($symbol, $depth),
            $symbol instanceof InterfaceNodeId => $this->interfaceGraph($symbol, $depth),
            $symbol instanceof EnumNodeId => $this->enumGraph($symbol, $depth),
        };
    }
}
