name: CI

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3
            tools: composer:v2
      - uses: "ramsey/composer-install@v3"
      - name: composer lint
        run: composer lint || echo "1"

  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3
            tools: composer:v2
      - uses: "ramsey/composer-install@v3"
      - name: composer test
        run: composer test

  build:
    runs-on: 'ubuntu-latest'
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
            php-version: 8.3
            tools: composer:v2
      - uses: "ramsey/composer-install@v3"
      - name: composer compile
        run: composer compile

