name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  phar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.37.0
        with:
          php-version: '8.4'
          extensions: ast
          tools: composer:v2
          ini-values: phar.readonly=0
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
      - run: composer compile
      - uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.6.1
        with:
          draft: false
          prerelease: false
          files: dist/peq.phar
